var GnoProj = require('../src/gnomonic')

console.log('Latitude = 0')
console.log(GnoProj.project(0,0))
console.log(GnoProj.project(0,'60W'))
console.log(GnoProj.project(0,'90W'))
console.log(GnoProj.project(0,180))
console.log(GnoProj.project(0,'120E'))
console.log(GnoProj.project(0,'90E'))
console.log('')

console.log('Latitude = 30')
console.log(GnoProj.project(30,0))
console.log(GnoProj.project(30,'60W'))
console.log(GnoProj.project(30,'90W'))
console.log(GnoProj.project(30,'120W'))
console.log(GnoProj.project(30,180))
console.log(GnoProj.project(30,'120E'))
console.log(GnoProj.project(30,'90E'))
console.log('')

console.log('Latitude = 45')
console.log(GnoProj.project(45,0))
console.log(GnoProj.project(45,'60W'))
console.log(GnoProj.project(45,'90W'))
console.log(GnoProj.project(45,180))
console.log(GnoProj.project(45,'120E'))
console.log(GnoProj.project(45,'90E'))
console.log('')

console.log('Latitude = 66.5')
console.log(GnoProj.project(66.5,0))
console.log(GnoProj.project(66.5,'60W'))
console.log(GnoProj.project(66.5,'90W'))
console.log(GnoProj.project(66.5,180))
console.log(GnoProj.project(66.5,'120E'))
console.log(GnoProj.project(66.5,'90E'))
console.log('')

console.log('Latitude = 90')
console.log(GnoProj.project(90,0))
console.log(GnoProj.project(90,'60W'))
console.log(GnoProj.project(90,'90W'))
console.log(GnoProj.project(90,180))
console.log(GnoProj.project(90,'120E'))
console.log(GnoProj.project(90,'90E'))